version: "3.7"

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: "wix_forms"
    volumes:
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  node_server:
    image: wix_node_server:latest
    environment:
      MONGODB_HOST: "mongodb://mongodb:27017/wix_forms"

  nginx_server:
    image: wix_nginx_server:latest
    ports:
      - 80:80
